# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/step',
                'doc_host': 'https://BorjaRequena.github.io',
                'git_url': 'https://github.com/BorjaRequena/step',
                'lib_path': 'step'},
  'syms': {'step.core': {'step.core.foo': ('core.html#foo', 'step/core.py')}}}
