# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/source/03_baselines.ipynb.

# %% auto 0
__all__ = ['ruptures_cp']

# %% ../nbs/source/03_baselines.ipynb 2
import numpy as np
from fastcore.all import *
from scipy.spatial import ConvexHull

# %% ../nbs/source/03_baselines.ipynb 16
import ruptures as rpt

# %% ../nbs/source/03_baselines.ipynb 17
@delegates(rpt.KernelCPD)
def ruptures_cp(x, pen=1., **kwargs):
    "Returns the change points of signal array x, excluding the initial and final times."
    alg = rpt.KernelCPD(**kwargs).fit(x)
    return alg.predict(pen=pen)[:-1]
